<%
  db_variables =
    ENV
      .filter { |key, _| key.start_with?("DISCOURSE_DB_VARIABLES_") }
      .transform_keys { |key| key.slice(("DISCOURSE_DB_VARIABLES_".length)..).downcase }

  dev_db_name = ENV['DISCOURSE_DB_NAME'] || ENV['DISCOURSE_DEV_DB'] || 'discourse_development'
  dev_db_host = ENV['DISCOURSE_DB_HOST'] || 'db'
  dev_db_port = ENV['DISCOURSE_DB_PORT'] || 5432
  dev_db_username = ENV['DISCOURSE_DB_USERNAME'] || 'postgres'
  dev_db_password = ENV['DISCOURSE_DB_PASSWORD'] || 'postgres'
%>

development:
  prepared_statements: false
  adapter: postgresql
  database: <%= dev_db_name %>
  username: <%= dev_db_username %>
  password: <%= dev_db_password %>
  host: <%= dev_db_host %>
  port: <%= dev_db_port %>
  min_messages: warning
  pool: 5
  checkout_timeout: <%= ENV['CHECKOUT_TIMEOUT'] || 5 %>
  host_names:
    - "<%= ENV['DISCOURSE_HOSTNAME'] || 'localhost' %>"
  variables: <%= db_variables.to_json %>

<%
  test_db = ENV["RAILS_DB"]
  if !test_db.present?
    test_db = "discourse_test"

    if num = ENV["TEST_ENV_NUMBER"]
      num = num.presence || "1"
      test_db += "_#{num}"
    end
  end
%>

test:
  prepared_statements: false
  adapter: postgresql
  database: <%= test_db %>
  min_messages: warning
  pool: 2
  reaping_frequency: 0
  checkout_timeout: <%= ENV["CHECKOUT_TIMEOUT"] || 5 %>
  host_names:
    - test.localhost
  variables: <%= db_variables.to_json %>

profile:
  prepared_statements: false
  adapter: postgresql
  database: discourse_profile
  min_messages: warning
  pool: 5
  host_names:
    - "localhost"
