<%
  db_variables =
    ENV
      .filter { |key, _| key.start_with?("DISCOURSE_DB_VARIABLES_") }
      .transform_keys { |key| key.slice(("DISCOURSE_DB_VARIABLES_".length)..).downcase }

  db_host = GlobalSetting.db_host || ENV["PGHOST"] || "postgres"
  db_port = GlobalSetting.db_port || ENV["PGPORT"] || 5432
  db_username = GlobalSetting.db_username || ENV["PGUSER"] || "postgres"
  db_password = GlobalSetting.db_password || ENV["PGPASSWORD"] || "postgres"
%>

development:
  prepared_statements: false
  adapter: postgresql
  host: <%= db_host %>
  port: <%= db_port %>
  username: <%= db_username %>
  password: <%= db_password %>
  database: <%= ENV['DISCOURSE_DEV_DB'] || GlobalSetting.db_name || 'discourse_development' %>
  min_messages: warning
  pool: 5
  checkout_timeout: <%= ENV['CHECKOUT_TIMEOUT'] || 5 %>
  host_names:
    - "<%= ENV['DISCOURSE_HOSTNAME'] || GlobalSetting.hostname || 'localhost' %>"
  variables: <%= db_variables.to_json %>

<%
  test_db = ENV["RAILS_DB"]
  if !test_db.present?
    test_db = "discourse_test"

    if num = ENV["TEST_ENV_NUMBER"]
      num = num.presence || "1"
      test_db += "_#{num}"
    end
  end
%>

test:
  prepared_statements: false
  adapter: postgresql
  host: <%= db_host %>
  port: <%= db_port %>
  username: <%= db_username %>
  password: <%= db_password %>
  database: <%= test_db %>
  min_messages: warning
  pool: 2
  reaping_frequency: 0
  checkout_timeout: <%= ENV["CHECKOUT_TIMEOUT"] || 5 %>
  host_names:
    - test.localhost
  variables: <%= db_variables.to_json %>

profile:
  prepared_statements: false
  adapter: postgresql
  host: <%= db_host %>
  port: <%= db_port %>
  username: <%= db_username %>
  password: <%= db_password %>
  database: discourse_profile
  min_messages: warning
  pool: 5
  host_names:
    - "localhost"
